import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Institute management system app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en"className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>

      <body className="bg-linear-to-r from-cyan-500 to-blue-500 min-h-full flex flex-col">
       
          {children}
          
      </body>

    </html>
  );
}
